microsoft/ConversationLearner-UI

- src/components/modals/EntityCreatorEditor.tsx
- src/components/modals/MemoryTable.tsx
> Change prefix for bulitin entities to builtin- instead of luis-

- src/components/modals/ActionPayloadEditor/OptionalPlugin.tsx
> Extend previous optional node around current text if user enters closing character adjacent / outside it

- src/components/ExtractorResponseEditor/ExtractorResponseEditor.tsx
- src/components/ExtractorResponseEditor/ExtractorResponseEditorContainer.tsx
- src/components/ExtractorResponseEditor/utilities.ts
Also use EntityType enum instead of LUIS constant since we're already using imports from conversationlearner/models
Closes VSTS#942
> Auto label selected text as the mostl recently added entity/option

- package-lock.json
- package.json
- src/components/modals/TeachSessionAdmin.tsx
- src/components/modals/TeachSessionModal.tsx
- src/routes/Apps/App/LogDialogs.tsx
- src/routes/Apps/App/TrainDialogs.tsx
Git Issue [#193](https://github.com/Microsoft/ConversationLearner-Samples/issues/193)
> 1350: prevent ending train dialog on non-terminal action

- package-lock.json
- package.json
- src/components/ToolTips.tsx
> 1354 - ClientMemoryManager no longer async

- src/components/modals/ActionScorer.tsx
- Use localeCompare for strings
- Differentiate between NotScoreable but still usable and NotScoreable and not usable.
>  bug(actionscorer): Fix sorting algorithm

- src/actions/createActions.ts
- src/components/ActionDetailsList.tsx
- src/components/ExtractorResponseEditor/CustomEntity.tsx
- src/components/ExtractorResponseEditor/CustomEntityNode.tsx
- src/components/ExtractorResponseEditor/EntityPicker.tsx
- src/components/ExtractorResponseEditor/EntityPickerContainer.tsx
- src/components/ExtractorResponseEditor/ExtractorResponseEditor.tsx
- src/components/ExtractorResponseEditor/FuseMatch.tsx
- src/components/ExtractorResponseEditor/PreBuiltEntity.tsx
- src/components/ExtractorResponseEditor/PreBuiltEntityNode.tsx
- src/components/HelpIcon.tsx
- src/components/actionPayloadRenderers/index.ts
- src/components/modals/ActionCreatorEditor.tsx
- src/components/modals/AdaptiveCardViewer/AdaptiveCardHostConfig.ts
- src/components/modals/EntityExtractor.tsx
- src/components/modals/ErrorPanel.tsx
- src/components/modals/Expando.tsx
- src/components/modals/PackageCreator.tsx
- src/components/modals/TutorialImporter.tsx
- src/routes/Apps/App/Actions.tsx
- src/routes/Apps/App/LogDialogs.tsx
- src/routes/Apps/App/TrainDialogs.tsx
- src/routes/Apps/AppsList.tsx
- src/routes/Settings.tsx
- src/services/client.ts
- src/services/clientFactory.ts
- src/services/sdkPort.ts
- tslint.json
Build outputs all TSLint warnings which are current so long they max out the Travis log UI length.  Hope to fix enough warnings or change rules to make it shorter
> chore: fix some tslint warnings

- package.json
- src/routes/Apps/App/Settings.tsx
* build: add commitizen config
>  style(settings): rename _APP_ID to _MODEL_ID

- package-lock.json
- package.json
- public/index.css
- src/actions/deleteActions.ts
- src/components/modals/ActionCreatorEditor.tsx
- src/components/modals/ConfirmCancelModal.tsx
- src/components/modals/EntityCreatorEditor.tsx
- src/components/modals/TrainDialogAdmin.tsx
- src/react-intl-messages.ts
- src/routes/Apps/App/Actions.tsx
chore: update @conversationlearner/models to 167
>  feat: allow deleting entities not used in payload or as suggested entity

- src/components/modals/EntityCreatorEditor.tsx
> fix: allow updating entity properties when not used

- cypress.json
- cypress/integration/helloworld_test.ts
- cypress/support/components/actionsmodal.js
- cypress/support/components/actionspage.js
- cypress/support/components/conversationsmodal.js
- cypress/support/components/entitypage.js
- cypress/support/components/homepage.js
- cypress/support/components/modelpage.js
- cypress/support/components/scorermodal.js
- cypress/support/components/traindialogspage.js
- changing function names to use camel case
- removing support file entry from cypress config
- and moving navigation functions inside the model page file
> test: changes to cypress test components functions

- src/components/HelpPanel.tsx
- src/components/modals/ErrorPanel.tsx
Fix is based on https://github.com/OfficeDev/office-ui-fabric-react/issues/3423#issuecomment-398469137
> fix: panel FocusTrapZone fix

- src/components/modals/AppCreator.tsx
- src/components/modals/EntityCreatorEditor.tsx
- src/components/tipComponents/DropdownWithTip.tsx
- src/routes/Apps/App/Settings.tsx
- src/routes/Apps/App/TrainDialogs.tsx
This should fix a11y issues until the bug is closed
https://github.com/OfficeDev/office-ui-fabric-react/issues/5347
> fix: explicitly set ariaLabel on OF.Dropdown components

- src/routes/Apps/App/Actions.tsx
- src/routes/Apps/App/Entities.tsx
- src/routes/Apps/App/LogDialogs.tsx
- src/routes/Apps/App/TrainDialogs.tsx
> fix: add labels to search inputs

- package-lock.json
- package.json
Doesn't really require this version of models, but it will be good to keep the UI and SDK on same version.
> fix: update @conversationlearner/models@0.168.1

- package-lock.json
- package.json
- src/components/Webchat.tsx
- src/components/modals/TeachSessionModal.tsx
fix: Webchat input bar element should not be tab-able when webwhat is disabled
fix: Webchat: disable upload image button as it isn't currently supported
> fix: webchat issues

- src/components/ExtractorResponseEditor/ExtractorResponseEditor.tsx
>  fix: prevent enter and merge_node

- package-lock.json
- package.json
fixes EPIPE error when running on windows and Node 10
> chore: update cypress to 3.0.2

- src/components/Webchat.tsx
- src/services/clientFactory.ts
- src/services/sdkPort.ts
Allows running SDK and directline to same port
As mentioned in previous PR goal is:
```
/api
/sdk
/directline
```
> fix: update for single port

- src/components/modals/ActionCreatorEditor.tsx
- src/services/client.ts
update client for editing to send actionId which is required for PUT requests
> fix: action editing

- src/components/modals/ErrorPanel.tsx
- src/index.tsx
- src/react-intl-messages.ts
- src/routes/App.tsx
- src/routes/Settings.tsx
- src/services/botPort.ts
- Also fix bug with how delay in botInfo prevented viewing settings page
> fix: auto port reset

- src/components/tipComponents/CheckboxWithTip.css
Hopefully this fixes the `inline-block` issue
> fix: cl-checkbox css specificity

- src/components/modals/ActionCreatorEditor.tsx
Match behavior of Entity Creator
> fix: only enable save button when state changes from initial state

- package-lock.json
- src/services/client.ts
>  fix: missing conversationid when editing entity 

- src/react-intl-messages.ts
> fix: more detailed warning when bot not found

- src/actions/createActions.ts
- src/actions/deleteActions.ts
- src/actions/updateActions.ts
- src/components/modals/EntityCreatorEditor.tsx
- src/services/client.ts
- When setting negatable, will also fetch newly created negatable entity and load it to memory
- When Unsetting negatable, will remove negatable entity from memory
> fix: editing negatable flag

- src/components/modals/ActionCreatorEditor.tsx
- src/types/PreBuiltEntities.ts
See: https://docs.microsoft.com/en-us/azure/cognitive-services/LUIS/luis-reference-prebuilt-deprecated
> fix: deprecated entities and remove prebuilts from suggested

- package-lock.json
- package.json
- src/components/ActionDetailsList.tsx
- src/components/ToolTips.tsx
- src/components/actionPayloadRenderers/ApiPayloadRendererContainer.tsx
- src/components/modals/ActionCreatorEditor.tsx
- src/components/modals/ActionScorer.tsx
- src/react-intl-messages.ts
- src/routes/Apps/App/Index.tsx
- src/routes/Apps/AppsList.tsx
chore: install conversation/models@0.172.0
>  feat: add ability to create RENDER actions

- package-lock.json
- package.json
- src/components/ActionDetailsList.tsx
- src/components/actionPayloadRenderers/ApiPayloadRenderer.css
- src/components/actionPayloadRenderers/ApiPayloadRenderer.tsx
- src/components/actionPayloadRenderers/ApiPayloadRendererContainer.tsx
- src/components/modals/ActionCreatorEditor.tsx
- src/components/modals/ActionScorer.tsx
- src/routes/Apps/App/Index.tsx
Needs more styling on the ActionCreatorEditor but is functional to unblock other team members.
> fix: split api actions into logic and render functions

- public/index.css
- src/components/CLTagPicker.tsx
- src/components/modals/ActionCreatorEditor.css
- src/components/modals/ActionCreatorEditor.tsx
- src/components/modals/EntityCreatorEditor.css
- src/components/modals/EntityCreatorEditor.tsx
- src/components/tipComponents/DropdownWithTip.tsx
- src/components/tipComponents/TagPickerWithTip.tsx
- restore consistent spacing between label and form elements
> fix: normalize label /form spacing

- public/index.css
- src/actions/appActions.ts
- src/components/modals/ActionCreatorEditor.tsx
chore: increase height of Action modal to reduce scroll jumping
chore: change polling logs to debug level to avoid noise
>  fix: onPayloadChange to use most up-to-date objects

- src/components/ExtractorResponseEditor/ExtractorResponseEditor.tsx
Also add check against adding label with empty text
> fix: prevent re-labeleing selected text

- BUILDING_UI_PACKAGE.md
* `onversationlearner` or `conversationlearner` on paragraphs #03 & 07?
* Plus minor fixes proposals
> Typo on string #42

- package-lock.json
- package.json
- src/ErrorInjector.ts
- src/components/HelpPanel.tsx
- src/components/ToolTips/ToolTipAPI.tsx
- src/components/ToolTips/ToolTips.tsx
- src/components/TrainingStatus.tsx
- src/components/TrainingStatusContainer.tsx
- src/components/Webchat.tsx
- src/components/modals/ActionCreatorEditor.tsx
- src/components/modals/EntityExtractor.tsx
- src/components/modals/ErrorPanel.tsx
- src/components/modals/MemoryTable.tsx
- src/components/modals/TeachSessionModal.tsx
- src/index.tsx
- src/routes/Apps/App/Dashboard.tsx
- src/routes/Apps/App/Index.tsx
- src/routes/Apps/App/LogDialogs.tsx
- src/routes/Apps/App/Settings.tsx
- src/routes/Apps/App/TrainDialogs.tsx
- src/routes/Apps/AppsIndex.tsx
- src/routes/Apps/AppsListComponent.tsx
- src/routes/Settings.tsx
- src/services/localStorage.ts
- src/services/poller.test.ts
- src/services/poller.ts
> fix: code cleanup

- appveyor.yml
to speed up build.  will need to manually invalidate the cache
> fix: remove cypress invalidation

- appveyor.yml
> fix: npm ci

- package-lock.json
- package.json
Render portion wasn't handling correctly
> fix: entities set in api callback working

- public/index.css
- src/components/modals/TeachSessionAdmin.tsx
Add training status container to traindialog, and flex inline
> fix: bug 1495 add training status to traindialog

- src/actions/teachActions.ts
- src/actions/trainActions.ts
- src/components/modals/EditDialogAdmin.tsx
- src/components/modals/EditDialogModal.tsx
- src/components/modals/EntityExtractor.tsx
- src/components/modals/TeachSessionAdmin.tsx
- src/components/modals/TeachSessionModal.tsx
- src/routes/Apps/App/LogDialogs.tsx
- src/routes/Apps/App/TrainDialogs.tsx
- src/services/client.ts
When editing filter out the train dialog being edited from the conflict checking
> feat: conflict filters

- src/components/ExtractorResponseEditor/EntityPicker.css
- src/components/ExtractorResponseEditor/EntityPicker.tsx
- src/routes/Apps/AppsListComponent.tsx
Switch from non-unique portion of the timestamp to fully qualified and expanded YYYYMMDDHHmmSS
> fix: bug 1541 - fix model date created sorting

- src/components/modals/TeachSessionAdmin.css
Rework margins to avoid overlapping status text
> fix: bug 1574 - overlapped status text

- public/index.css
- src/components/modals/EditDialogAdmin.css
- src/components/modals/EditDialogAdmin.tsx
- src/components/modals/TeachSessionAdmin.css
- src/components/modals/TeachSessionAdmin.tsx
Wrapped content in new css class set, with fixed height flexbox
> fix: bug 1574 - prevent status text overlap

- src/components/modals/ActionCreatorEditor.tsx
Boost the contextual information conveyed to the users for key inputs
> feat: Improved action creator dialog input labels

- src/components/HelpPanel.tsx
> fix: bug 1610 - restyle help panel close button

- public/index.css
- src/components/HelpPanel.tsx
Now leverage the Fabric footer hook to simplify our panel's footer area
> fix: 1610 - close button as footer bar

- src/Utils/util.ts
- src/components/modals/ActionScorer.tsx
- src/react-intl-messages.ts
Fix up merge conflicts, and get helper utils into mainline & code review comments
> fix: 1105BugBash.C (#1582)

- src/components/modals/ActionScorer.tsx
- src/components/modals/ConfirmCancelModal.tsx
- src/components/modals/EntityExtractor.tsx
- src/components/modals/ExtractConflictModal.tsx
- src/components/modals/MemoryTable.tsx
- src/components/modals/TeachSessionModal.tsx
- src/components/modals/TutorialImporter.tsx
- src/routes/Apps/App/LogDialogs.tsx
- src/routes/Apps/App/Settings.tsx
- src/routes/Apps/App/TrainDialogs.tsx
- src/routes/Apps/AppsListComponent.tsx
> fix: bug 1639

- src/actions/trainActions.ts
- src/reducers/appsReducer.ts
- src/types/ActionObject.ts
Now hooks the app reducer and modal actions to set lastmodified to the current system time (in ISO 8601 format)
> fix: bug 1581 - model lastmodified date

- src/react-intl-messages.ts
- src/routes/Apps/App/TrainDialogs.tsx
Clearer placeholder text for entity and action filters
> fix: bug 1661 - improved placeholder text for filters

- src/components/modals/ChatSessionModal.tsx
- src/routes/Apps/App/LogDialogs.tsx
Added ESC key handling for quick key/close
> task: task 1662 - add ability to close log dialog quickly

- src/react-intl-messages.ts
- src/routes/Apps/App/TrainDialogs.tsx
Added clarity to the drop down labels, and cleaned up the "any" option
> fix: bug 1661 - more concise filtering dropdown labels & "any"

- src/routes/Apps/AppsListComponent.tsx
Reworked so today's timestamps show HH:MM vs current MM/DD/YYYY
> fix: bug 1681 smarter model creation & last updated times

- src/Utils/util.ts
- src/components/ActionDetailsList.tsx
- src/routes/Apps/App/Entities.tsx
- src/routes/Apps/App/LogDialogs.tsx
- src/routes/Apps/App/TrainDialogs.tsx
- src/routes/Apps/AppsListComponent.tsx
Promote the momentjs helper wrapper so it's available to the entire project, not just to the train dialog gridview
> fix: bug 1681 - smarter create/lastmodified display

- src/routes/Apps/App/LogDialogs.tsx
Zapped the lastModifiedtime column completely
> fix: bug 1715 - pull lastModifiedtime from Log Dialogs grid view

- src/components/modals/AppCreator.tsx
Support ENTER key press once name & file selected; ignore otherwise
> fix: bug 1700 - support ENTER on model import if name & file selected

- cypress/integration/Tests/(All).js
- cypress/support/TestListManager.js
- cypress/support/commands.js
Not sure why the code ever worked with this "DoesNotContain" function in there, but its gone now.
> fix: removed a duplicate function

- cypress/support/Helpers.js
- cypress/support/TestListManager.js
Chat messages recently had HTML added to them, I had to remove the markup in order to validate the text.
> Remove Markup Bug Fix

- src/components/modals/PackageCreator.tsx
trim value parameter received during synthesized change event
> fix: bug 1758 - block second MASTER tag

- cypress/fixtures/z-travel.cl
- cypress/support/Entities.js
- cypress/support/Helpers.js
- cypress/support/TestListManager.js
- cypress/support/components/EntityModal.js
- cypress/tests/CreateModels.js
- cypress/tests/Train.js
2 new test cases for Entity Resolver Types modeled after "Entity Resolvers" tutorial video.
> Entity Resolver Types Test Cases

- cypress/support/components/HomePage.js
fix: ui changed - now needs model name to confirm delete
> Fix Delete All Test Case

- public/index.css
- src/components/modals/TextboxRestrictable.tsx
- src/react-intl-messages.ts
- src/routes/Apps/App/Index.tsx
- src/routes/Apps/App/Settings.tsx
- src/routes/Apps/AppsList.tsx
- src/routes/Apps/AppsListComponent.tsx
Moving deletion to Settings, and away from the current, easier and more error prone App listview
> Task 1817 - move deletion to Settings

- src/components/Webchat.tsx
Shouldn't unsubscribe from BehaviorSubject directly
> fix: unsubscribing from behavior subject

- src/routes/Apps/App/LogDialogs.tsx
Set column to the creation date (column#5) in the constructor, and set the default sort to descending
> fix: sort by creation date, descending

- src/Utils/dialogUtils.test.ts
- src/Utils/dialogUtils.ts
- src/Utils/testDataUtil.ts
- src/components/modals/TreeView/TreeNodeLabel.tsx
- src/components/modals/TreeView/TreeView.tsx
Pre-work needed for being able to merge train dialogs
some additional code cleanup on treeview
> feat: utilities for finding matching train dialogs

- src/Utils/dialogUtils.tsx
- src/actions/chatActions.ts
- src/actions/logActions.ts
- src/components/modals/ChatSessionModal.tsx
- src/routes/Apps/App/LogDialogs.tsx
- src/types/ActionObject.ts
- delete log dialog when editing and saving log dialog
> fix: bug 1972 tags and description not saved on logs

- src/components/ExtractorResponseEditor/EntityPickerContainer.tsx
> fix: don't reset matched options

- src/components/ToolTips/ToolTips.tsx
Correct the urls used in the help panel tip to be relative
Fixes ADO#2004, ADO#1994
> fix: entity tooltip gifs

- src/actions/chatActions.ts
> fix: bug 2024 abandoned log dialogs don't always go away

- public/index.css
- src/components/modals/TeachSessionModal.tsx
tweaked positioning of debug marker
> fix: bug 2031 description and tags leak to subsequent train dialog

- src/components/modals/TreeView/TreeView.css
- src/components/modals/TreeView/TreeView.tsx
- src/react-intl-messages.ts
- src/routes/Apps/App/TrainDialogs.tsx
TreeView shown w/in regular model page with expando
> fix: tree view fixes

- public/index.html
> fix: prevent caching UI

- src/components/modals/DialogMetadata.tsx
- src/components/modals/MergeModal.tsx
- src/react-intl-messages.ts
Change ordering and show alt text
> fix: bug 2079 change display of merge dialog

- src/components/modals/ActionCreatorEditor.css
- src/components/modals/ActionCreatorEditor.tsx
- src/components/modals/PackageCreator.tsx
- src/components/modals/TextboxRestrictable.tsx
- src/components/modals/UserInputModal.tsx
- src/routes/App.css
- src/routes/Apps/App/LogDialogs.tsx
Not sure what is going with the other PR, trying to isolate by splitting up further.
Will update the other depending PR's if this succeeds and is merged.
> fix: log dialog testids, css selectors fixes, and package creator modal

- package-lock.json
- package.json
- src/components/ToolTips/ToolTips.tsx
- src/components/modals/MemoryTable.tsx
- src/types/PreBuiltEntities.ts
As discussed on Teams, update to keep closer parity with LUIS capabilities
> feat: add new prebuilts (geographyV2, personName, keyPhrase)

- cypress/support/components/ActionModal.js
- src/components/modals/ActionCreatorEditor.tsx
Matt advised me on better names for data-testids in a prior pull request. This change did not make it in that PR, so here it is now.
> Fix data-testid as advised

- .circleci/config.yml
Now that the `test-ApiCallbacks` file is merged back into `develop` branch for Smoke tests this UI CI config can use it there.  Also ensures changes to that file go through PR
> build: use develop branch, add comments

- package-lock.json
- package.json
- src/routes/Apps/App/TrainDialogs.tsx
> feat: validatation test cancel

- src/routes/Apps/App/TrainDialogs.tsx
> fix: train dialog description sort

- package-lock.json
- package.json
- src/Utils/util.ts
OF 5.x needed the lower version of typescript but now that we're on 6.x we can upgrade
> build: upgrade typescript

- package-lock.json
- package.json
> fix: bug 2163 overlapping entities results in bad input render

- cypress/fixtures/z-bug2202Repro.cl
- cypress/integration/Regression/EditAndBranching/Bug2202Repro.spec.js
This test suite reproduces [Bug 2202: FETCH_TRAINDIALOGREPLAY_ASYNC Failed: nasty error came up](https://dialearn.visualstudio.com/BLIS/_workitems/edit/2202)
> Test suite to reproduce Bug 2202

- cypress/fixtures/z-bug2202Repro.cl
- cypress/integration/Regression/EditAndBranching/Bug2202Repro.spec.js
- cypress/integration/Regression/ErrorHandling/BotMissingApi.spec.js
- cypress/support/Actions.js
- cypress/support/Helpers.js
- cypress/support/components/ActionModal.js
- cypress/support/components/ModelPage.js
- cypress/support/components/ScorerModal.js
- Product bug was fixed by Lars, test code adjusted to pass only when the bug does NOT reproduce.
- Cleaned up the hacky code and fixed bug in BotMissingApi.spec.js
> Bug2202 Repro Test Suite for Fixed Product Bug

- src/Utils/dialogUtils.tsx
- src/components/modals/ActionScorer.tsx
- src/components/modals/EditDialogModal.tsx
- src/routes/Apps/App/Index.tsx
- src/routes/Apps/App/LogDialogs.tsx
- src/routes/Apps/App/TrainDialogs.tsx
Not merging yet, but want your feedback.  Thanks!
> style: edit modal uses query param

- package-lock.json
- package.json
- src/components/IndexButtons.css
- src/components/IndexButtons.tsx
- src/components/modals/ActionCreatorEditor.tsx
- src/components/modals/AdaptiveCardViewer/AdaptiveCardViewer.tsx
- src/components/modals/CompareDialogsModal.css
- src/components/modals/CompareDialogsModal.tsx
- src/react-intl-messages.ts
update webchat to fix scroll bug
> feat: moved prev / next buttons into shareable component

- cypress/integration/Regression/EndSession/AutoScoreEndSessionAction.spec.js
- cypress/support/Train.js
This is a test case to demonstrate bug 2927 and then later verify that the bug is fixed.
> Auto Score End Session Action

- package-lock.json
- package.json
- src/components/ActionDetailsList.tsx
- src/components/modals/ActionCreatorEditor.tsx
- src/react-intl-messages.ts
- src/routes/Apps/AppsIndex.tsx
Depends on the SDK understanding these new types, and the server and trainer accepting them.
> feat: use DISPATCH actions instead of overloading TEXT actions

- cypress/integration/Regression/EditAndBranching/Bug2259Repro.spec.js
A simple test to reproduce and later verify that bug 2259 does not regress.
> fix: working bug 2259 reproduction test case

- src/components/modals/EntityCreatorEditor/EntityCreatorContainer.tsx
- src/react-intl-messages.ts
> fix: enum value max length

- src/routes/Apps/App/LogDialogs.tsx
- src/routes/Apps/App/TrainDialogs.tsx
- Use parsed payload instead of raw json payload for search
- Fix regression from Fabric 7 upgrade
> fix: log dialog search filter

- src/components/modals/CompareDialogsModal.tsx
- src/components/modals/RateDialogsModal.tsx
- src/routes/Apps/App/LogDialogs.tsx
- src/services/client.ts
Mainly needed to do another PR to force release. Also updated things missed in first PR
> fix: change fromhistory to fromtraindialog

- src/components/actionPayloadRenderers/ApiPayloadRendererWithHighlights.tsx
> fix: code action name

- src/Utils/dialogEditing.ts
- src/components/modals/ActionCreatorEditor.tsx
- src/react-intl-messages.ts
Addressing comments from https://github.com/microsoft/ConversationLearner-UI/pull/1321
> fix: Updates for comments missed in previous isEntry PR

- src/components/ToolTips/ToolTips.tsx
- src/components/modals/ActionCreatorEditor.tsx
- src/react-intl-messages.ts
- src/types/models.ts
More housekeeping.  Tested against local build.
> refactor: update more "entryNode" instances to "isEntryNode"

- package-lock.json
- package.json
- src/components/Webchat.tsx
- src/components/modals/CompareDialogsModal.css
- src/components/modals/CompareDialogsModal.tsx
- src/components/modals/RateDialogsModal.tsx
- src/components/modals/TranscriptRatings.tsx
- src/types/TestObjects.ts
- src/types/models.ts
compare and ratings view are aligned by adding padding
view scroll together more smoothly
a few other improvements
> feat: aligned webchats

- package-lock.json
- package.json
- src/Utils/dialogEditing.ts
- src/Utils/dialogUtils.tsx
- src/Utils/obiDialogParser.ts
- src/Utils/obiTranscriptParser.ts
- src/Utils/obiUtils.tsx
- src/Utils/util.ts
- src/components/Webchat.tsx
- src/components/modals/ActionCreatorEditor.tsx
- src/components/modals/AppCreator.tsx
- src/components/modals/CompareDialogsModal.tsx
- src/components/modals/EditDialogAdmin.tsx
- src/components/modals/EditDialogModal.tsx
- src/components/modals/RateDialogsModal.tsx
- src/components/modals/TeachSessionModal.tsx
- src/components/modals/TranscriptComparisons.tsx
- src/components/modals/TranscriptList.tsx
- src/components/modals/TranscriptRatings.tsx
- src/routes/Apps/App/LogDialogs.tsx
- src/routes/Apps/App/Testing.tsx
- src/routes/Apps/App/TrainDialogs.tsx
- src/types/TestObjects.ts
- src/types/models.ts
- elminate multple sources of Activity definition
- rename validationSet to testSet
- store transcript with lgName only
- add lgName to action when matched
> feat: attach lg name to action 

- src/Utils/obiDialogParser.ts
- src/routes/Apps/App/TrainDialogs.tsx
- src/types/TestObject.test.ts
- src/types/TestObjects.ts
decreases number of required user ratings
> feat: transcript ratings are transitive

- package-lock.json
- package.json
- src/Utils/obiDialogParser.ts
- src/components/modals/EntityCreatorEditor/EntityCreatorContainer.tsx
Minor change to depend on new constants.
> refactor: use new enum constants from Models repo

- .circleci/SetLuisAuthoringKey.js
- .circleci/config.yml
- Run smoke and regression tests in parallel
- Base authoring key off of build number%5
> Trying for a better build process

- src/components/LogDialogEditor.tsx
- src/routes/Apps/App/LogDialogs.tsx
Separate LogDialog editing from the LogDialog page.   This allows log editing to take place on other pages (in prep from Review page).  Also, with some additional work will help us unify editing with the TrainDialog page.
> feat: logdialogeditor

- cypress/support/components/TrainingStatus.js
- Lengthen the wait for Running to Completed transition to 2 minutes
- Added some additional information to the logs
> Minor Traning Status Monitoring Improvements

- package-lock.json
- package.json
Add script from: https://create-react-app.dev/docs/analyzing-the-bundle-size/
At least now we can see the issues, if it becomes more of a problem (mainly concerned about the increasingly long refresh/build times during development) we can look at solving them later.
> chore: add build size analyzer

- src/components/modals/ConditionModal.tsx
OF bug:  https://github.com/OfficeDev/office-ui-fabric-react/issues/11358
> fix: add min max on spinbutton
