microsoft/ConversationLearner-UI

- src/components/ExtractorResponseEditor/ExtractorResponseEditor.tsx
From what I understand the browser asynchronously updates the selection object and so there are scenarios where the rangeCount is not updated by the time we query it.  We previously were blindly calling getRangeAt(0) but there were no ranges.  This is like trying to access element on array which is empty.  We now check the length first.
https://developer.mozilla.org/en-US/docs/Web/API/Selection/getRangeAt
Fixes VSTS#1333
> [Bug]: Only call getRangeAt(0) if rangeCount > 0

- .vscode/settings.json
- CredScanSuppression.json
- package-lock.json
- package.json
- src/components/ActionDetailsList.tsx
- src/components/ExtractorResponseEditor/utilities.ts
- src/components/TextPayloadRenderer.css
- src/components/TextPayloadRenderer.tsx
- src/components/actionPayloadRenderers/ApiPayloadRenderer.css
- src/components/actionPayloadRenderers/ApiPayloadRenderer.tsx
- src/components/actionPayloadRenderers/ApiPayloadRendererContainer.tsx
- src/components/actionPayloadRenderers/CardPayloadRenderer.css
- src/components/actionPayloadRenderers/CardPayloadRenderer.tsx
- src/components/actionPayloadRenderers/CardPayloadRendererContainer.tsx
- src/components/actionPayloadRenderers/TextPayloadRenderer.css
- src/components/actionPayloadRenderers/TextPayloadRenderer.tsx
- src/components/actionPayloadRenderers/TextPayloadRendererContainer.tsx
- src/components/actionPayloadRenderers/index.ts
- src/components/modals/ActionCreatorEditor.tsx
- src/components/modals/ActionPayloadEditor/index.ts
- src/components/modals/ActionPayloadEditor/slateSerializer.test.ts
- src/components/modals/ActionPayloadEditor/slateSerializer.ts
- src/components/modals/ActionPayloadEditor/slateTransformer.ts
- src/components/modals/ActionScorer.tsx
- src/components/modals/EntityExtractor.tsx
- src/routes/Apps/App/TrainDialogs.tsx
- src/util.ts
- Use same component across ActionDetailsList and ActionScorer to ensure consistency
- Allow viewing original form of action without entity substitutions
- Allows viewing partially complete payloads (they have required entity which is missing and disqualified but still want to see substitutions)
- Allows viewing cards in both states
Optional brackets are now correctly shown to indicate optional sections:
Api payloads show arguments to the user as they would appear in the function so they better understand the relationship:
Showing current memory (notice e1 value 3457 is showing):
Toggle to show original text (notice 3457 is not shown):
Card Previews can now show with current memory for better idea of what bot will return:
> Allow users to view most up to date payload when selecting actions with toggle for original text.

- appveyor.yml
I think if failure occurred in after_success it might not catch it so moving build to actual build phase
> Add skip_branch_with_pr and build before test

- src/components/ToolTips.tsx
- src/components/modals/AppCreator.tsx
- src/components/modals/EntityCreatorEditor.tsx
- src/components/modals/PackageCreator.tsx
- src/react-intl-messages.ts
- src/routes/App.tsx
- src/routes/Apps/App/Dashboard.tsx
- src/routes/Apps/App/Index.tsx
- src/routes/Apps/App/Settings.tsx
- src/routes/Apps/AppsIndex.tsx
- src/routes/Apps/AppsList.tsx
- src/routes/NoMatch.tsx
The term application has a lot of other meaning and sounds like the root logical container for a system.  However, multiple CL 'application' could have been used in a single bot which is also an "application".  The term model is more appropriate semantically.  You are training conversation models for different task based domains and may use one or more of them within your Application / Bot.
> Rename visible text using 'Apps' or 'Applications' to 'Models'

- scripts/publish.ts
Accidentally broke builduipackage command when removing the version detection and git tagging
> ci: fix builduipackage script

- .circleci/config.yml
Example of Cypress dashboard output for test run:
https://dashboard.cypress.io/#/projects/so64kq/runs/8/specs
Currently the tests only pass with Chrome, but Cypress recording only works with electron which means we don't have recordings yet.  I'm still trying to find out why they're broken on Electron.
>  ci: update circle CI config to build sample and run e2e tests

- .circleci/config.yml
- config-mocha-reporter.json
- cypress.json
- package-lock.json
- package.json
This allows best of both reports.  Inline spec reports to be uploaded by Cypress with standard test result output saved as artifact to be understood by CI tool
> ci: setup mocha-multi-reporters to show spec and save junit

- src/routes/Apps/App/Actions.tsx
Related to our mis-use of Office Fabric detail list. We're using the `onActiveItemChanged` as hack to enable response to single click. However, this means once the item is clicked and modal is closed that row is still active so clicking it again will not trigger the same event.  Then we add another hack which is to change the focus of element.
In the long term we should likely replace our list component, but in short term this just changes focus to new action button similar to entities page.
> fix: allow opening action editor on same row

- package-lock.json
- package.json
- src/actions/createActions.ts
- src/services/client.ts
Previous this required 3 steps:
1. Create positive entity
2. Create negative entity using positive entity id
3. Update positive entity with negative entity id
Now we can do all of this with one call:
1. Create entity (if negatable is true, implicitly create negative entity as well)
We still have to fetch the negative entity since we need representation of it in memory though.
>  fix: allow negative entity creation in single call

- src/actions/deleteActions.ts
- src/routes/Apps/App/Entities.tsx
I had fixed entity creation to be single call, but this will also address the delete.
Entities with associated negative entities will be created and deleted as pairs now.
> fix: delete entity in single call

- src/routes/Apps/App/Actions.tsx
- src/routes/Apps/App/Entities.tsx
- src/routes/Apps/App/Index.css
- src/routes/Apps/App/LogDialogs.tsx
- src/routes/Apps/App/TrainDialogs.tsx
Not as clean as I had thought it would be.
- Originally wanted to add some gifs explaining each item, but gif was only really help for entities.
There isn't easy way to distinguish between a dialog. What really matters is the source of content and role developer plays and that would need a custom graphic.
- I also was going to remove the redundant "new" buttons, but the other "new" buttons have the component reference that sets focus on every re-fresh and removing it was going to increase complexity
Fixes VSTS#916
> fix: add placeholders for empty lists

- cypress/integration/create_app.ts
- cypress/integration/waitvsnonwait_actions_test.ts
- cypress/support/components/actionsmodal.js
- cypress/support/components/actionspage.js
- cypress/support/components/entitymodal.js
- cypress/support/components/homepage.js
- cypress/support/components/logdialogmodal.js
- cypress/support/components/logdialogspage.js
- cypress/support/components/scorermodal.js
- cypress/support/components/traindialogmodal.js
- src/components/modals/EntityCreatorEditor.tsx
- implementation of new test to validate the use of Wait Actions VS Non Wait Actions during the train dialog creation.
Wait action: After the system takes a "wait" action, it will stop taking actions and wait for user input.
Non-wait action: After the system takes a "non-wait" action, it will immediately choose another action (without waiting for user input)
Also, added new  data-testids for entity creation checkboxes.
finally, I also modified function names to match action + element name.
> test: adding wait vs non wait actions test

- cypress.json
Currently there are intermittent failures  happening around requests to our services.
This change will allow cypress to wait for the requests to complete before proceeding with next validations/steps even in remote environment execution.
> increasing requestTimeout

- src/actions/createActions.ts
- src/actions/deleteActions.ts
- src/actions/fetchActions.ts
- src/actions/teachActions.ts
- src/actions/updateActions.ts
- src/components/modals/AppCreator.tsx
- src/components/modals/ChatSessionModal.tsx
- src/components/modals/ErrorPanel.tsx
- src/epics/apiHelpers.ts
- src/reducers/errorReducer.ts
- src/types/StateTypes.ts
- Use AxiosError instead of Error when setting display
- Parse message outside of panel
- Remove manually managed key
- Use type and title instead of redundant error properties
>  fix: normalize error code

- cypress.json
- screen default values (1000x660) won't  let the screenshots to view all the elements; this change sets the viewport values to 1600x900 which is a decent size and allow us to see more details.
sample:  https://dashboard.cypress.io/#/projects/so64kq/runs/129/failures/277d8d7f-5797-4ab1-ac23-92301b0e5a8a
- Some request are still taking long (sample below):
https://dashboard.cypress.io/#/projects/so64kq/runs/108/failures/bd119809-8068-47cb-92c5-a1bc0e7a0422 (see delete test step failure)
> test: cypress configuration updates

- src/components/ExtractorResponseEditor/ExtractorResponseEditor.tsx
Apparently "merge_node" is used in some cases so this should not be disallowed
> fix: restore merge_node operation

- src/routes/Apps/App/LogDialogs.tsx
- src/routes/Apps/App/Settings.tsx
- src/routes/Apps/AppsList.tsx
It follows pattern from home page where all commands on the list below are in row at top.
Allow button to be used even when there are no log dialogs
Fixes: VSTS#1419
>  fix: move logdialog refresh button to top

- src/services/client.ts
Now that SDK is only passing through requests and not manipulating them, UI must properly construct requests
>  fix(client): update client to account for changes to SDK

- src/actions/fetchActions.ts
- src/components/modals/ActionCreatorEditor.tsx
- src/epics/apiHelpers.ts
- src/epics/fetchEpics.ts
- src/routes/App.tsx
- src/routes/Apps/App/Dashboard.tsx
- src/routes/Apps/App/Index.tsx
- src/routes/Apps/AppsIndex.tsx
previously the app would redirect back to /home from /apps/:appId pages
> fix: allow refresh/resume on app specific pages

- src/reduxStore.ts
I had added in the check for resetting default port after the persisted state object had already been created on my machine so I missed this.  Compounded with other issue of this project not having `strictNullChecks` allowed TypeScript to mask that the persistedState was possibly `undefined` even though the `load` function explicitly says it returns `T | undefined`
Fixes #657
> fix: handle undefined persisted state

- src/components/ExtractorResponseEditor/CustomEntity.tsx
- src/components/ExtractorResponseEditor/ExtractorResponseEditor.tsx
Previously there was only a Button element, but the new button from OF also has an Icon element inside it that seems to confuse the poicker.  Even when clicking on the portion of the button outside the icon it still seems to return the icon element and I'm not sure why, but this will at least mitigate the issue.
> fix: include 'I' as tag name to ignore

- src/actions/fetchActions.ts
- src/components/modals/ActionCreatorEditor.tsx
- src/routes/Apps/App/Dashboard.tsx
- src/routes/Apps/App/Index.tsx
- src/services/client.ts
- src/types/ActionObject.ts
Required for multi-model application to support loading right APIs
> fix: fetchbotinfo takes appid

- src/components/modals/TrainDialogAdmin.tsx
There was bug with asserting 0 as truthy from commit: `a619d458`
> fix: viewing train rounds

- src/actions/teachActions.ts
- src/components/modals/EntityExtractor.tsx
- src/components/modals/LogDialogAdmin.tsx
- src/components/modals/LogDialogModal.tsx
- src/components/modals/TrainDialogAdmin.tsx
- src/components/modals/TrainDialogModal.tsx
- src/routes/Apps/App/LogDialogs.tsx
- src/routes/Apps/App/TrainDialogs.tsx
I wonder why newScoreInput was sent, but I think it's better to not have null going through so many layers.  From admin, modal, then list page, then to action only to be evaluated based on non-null
>  fix: ability to view and edit train rounds

- src/components/modals/ActionCreatorEditor.tsx
Fixes VSTS#1477 Save button should be enabled after toggling the wait/non-await checkbox.
> fix: use isTerminal in computation for pending changes

- src/actions/appActions.ts
- src/services/poller.test.ts
- src/services/poller.ts
If you trigger training and then delete an app, it would have still polled until the timeout and each request would fail since that app no longer exists. This will now remove / stop the polling after successful deletion.
>  fix: add ability to remove poll after deleting app

- public/index.css
- src/components/modals/ActionScorer.tsx
- src/components/modals/EditDialogAdmin.tsx
- src/components/modals/EditDialogModal.tsx
- src/components/modals/TeachSessionAdmin.tsx
- src/components/modals/TeachSessionModal.tsx
- src/components/modals/index.ts
- src/react-intl-messages.ts
- src/routes/App.css
- src/routes/Apps/App/LogDialogs.tsx
- src/routes/Apps/App/TrainDialogs.tsx
- src/services/client.ts
Can't add action to last user input at bottom
Log dialog before edit - abandon button should be delete
Add delete button to logdialogs when not edit
Can save as train dialog when running wrong bot.  Shouldn't be allowed
Failed to delete train dialog right after converting from log
Disable turn editing when can't edit
> fix: misc bugs

- package-lock.json
- package.json
- public/botchat.css
- public/index.css
- src/components/Webchat.tsx
- src/components/modals/AddButton.css
- src/components/modals/AddButtonInput.tsx
- src/components/modals/AddButtonScore.tsx
- src/components/modals/EditDialogModal.tsx
- src/components/modals/TeachSessionModal.tsx
- src/react-intl-messages.ts
- src/routes/Apps/App/LogDialogs.tsx
- src/routes/Apps/App/TrainDialogs.tsx
Error when editing log dialog and saving it as a new train dialog
add tips on icons when you are editing a train dialog
Can't save with dummy last round, need to clean
Make edit icons look better
the bot response is added below the existing bot response / not above as expected.
Switch sub-bubble text to always be "user" and "bot:"
Text in webchat control for the source: would be good to say “User” & “Bot”
Sometimes the source is: “Bot at Invalid date”
Refactor webchat rendering
Better way to show that next step bot response when on bottom of page
> feat: Edit polish

- package-lock.json
- package.json
- src/actions/entityActions.ts
- src/components/modals/ActionCreatorEditor.tsx
- src/components/modals/TeachSessionAdmin.tsx
- src/components/modals/TeachSessionModal.tsx
- src/reducers/appsReducer.ts
1490: Entity Memory is "Empty" on a new train dialog AFTER "Set Initial State" is used
1498: Update training status to running immediately when polling starts
1491 Create Entity and Action Dialogs Need Consistent Cancel Behavior
> feat: init memory fixes

- src/components/modals/ActionCreatorEditor.tsx
1508: Edit existing action.  Delete a required entity and the "save" button is still disabled
> fix: bug 1508

- src/routes/Apps/App/TrainDialogs.tsx
Whoops, you couldn't undo filter selections. Now, the "---" is "--any--" and the filtering logic actually recognizes as <any>
> fix: bug 1589 - filter de-selection

- src/routes/Apps/AppsListComponent.tsx
Column sorting now better, with single sort indicator and corrected directionality. Slightly new behavior as well; columns remember their sort order, so next click back on them flips their previous order
> fix: bug 1542 - column sorting inconsistency

- src/components/modals/TeachSessionAdmin.tsx
- src/routes/Apps/App/TrainDialogs.tsx
Status area now includes a little right side margin bumper. Bumped up the area's allocation a bit while here
> fix: bug 1593; scroll bar hides status text

- src/routes/Apps/App/TrainDialogs.tsx
Switched to computed equality of column width based on overall screen width.  And directed the DetailedList component to consider the min/max
> fea: 1515 - better allocate column width

- src/routes/Apps/App/Index.tsx
Introduce new state element to configure gui to zero vitals while models switch across all required async thunks
> fix: 1586 - stale model data during model switch

- src/components/HelpIcon.tsx
Set control's background to transparent and important to override Fabric's, yet handle colorized messages
> fix: bug 1642 - help icons need transparent background, not hardcoded

- src/components/modals/ErrorPanel.tsx
UX guidelines have the close buttons flush right
> fix: bug 1675 - UX: shove error panel close button flush right

- src/components/modals/UserInputModal.tsx
We were trapping long input values on the button handlers, but not Enter. Now check on keydown events as well
> fix: bug 1665 - check value length inside ENTER handler too

- src/Utils/util.ts
Requested feature change; display HH:MM if the timestamp is less than 24 hours difference for timestamps
> fix: bug 1697 - switch timestamp logic to consider span, not calendar days

- src/react-intl-messages.ts
Mirroring the corrected text in the actual webchat error string
> fix: bug 1702 - fix typo in tool tips, sys error message

- public/manifest.json
Corrected the manifest size information to the actual 48 pixel square dimensions
> fix: bug 1775 - fix favicon.ico size error, shown in console

- src/components/modals/EntityCreatorEditor/EntityCreatorComponent.tsx
Invoke the native DOM focus() handler via ref
> fix: bug 1672 - set focus on entity name by default

- src/components/modals/PackageCreator.tsx
Reworked the name checking logic a bit, and add name checking to ENTER/keydown logic
> fix: bug 1758 - block second "master" tag

- src/components/modals/TextboxRestrictable.tsx
- src/react-intl-messages.ts
- src/routes/Apps/AppsListComponent.tsx
Created new textbox-centric modal to support model name typing to confirm model deletion. New modal better supports generic modal dialog box-ing by abstracting away strings and button event handling
> fix: task 1699 - require model name typed for deletion

- src/components/actionPayloadRenderers/SessionPayloadRendererContainer.tsx
Session actions were quite start w/just the payload's value displayed in detailed view. Now, prefix with "EndSession:"
> feat: feature 1835 - enhance session label in detailed views

- src/actions/trainActions.ts
- src/components/modals/EditDialogModal.tsx
Added request for model training status in `createTrainDialogThunkAsync`
It seemed like this thunk was on two different modal: `EditModalDialog` and `TeachSessionModal`
In my searching it seems we create train dialogs in three cases.
1. New Train Dialog button
TeachSession -> prop.onClose -> onCloseTeachSession(true) -> deleteTeachSession (Implicitly creates train dialog and does polling)
2. Branch train dialog
If you click branch, enter new input, and immediately click save without adding new scorer rounds we didn't poll for training either which I think was another related bug. This also used the `createTrainDialogThunkAsync` so this fix also addressed that issue.
3. Convert Log Dialog to Train Dialog
onClickConvert -> onSave -> createTrainDialogThunkAsync
Even if this some times adds …
>  fix: add requests for model training to missing cases

- .gitignore
- package-lock.json
- package.json
- public/index.html
- server/server.ts
- server/tsconfig.json
- src/routes/App.tsx
- tsconfig.json
Currently we require a separate command to serve the UI. This runs the bot on a separate port from the bot and serves it at the root.
Goals:
- This PR will change the package output so the UI can be served at `/ui` path.
- Development remains unchanged! You can still `npm start` and view at `localhost:5050/`
- Tests run from CircleCI should remain unchanged because they use 
Also added a `server` folder which allows testing the built package and seeing that it works on the `/ui` path.
> feat: allow interface to be served at /ui path

- src/routes/Apps/App/Index.tsx
I didn't catch this the first review. The conditional operator evaluated `this.state.modelLoaded && (this.props.logDialogs.length > TRIPLE_DIGIT_LOGDIALOG_COUNT)` as an expression which was false so it displayed the false value of `this.props.logDialogs.length` when it should not have. Wrapping extra parenthasis ensures if the model has not loaded the conditional operator won't evalaute and the whole thing will return false which React won't render.
> fix: only show log dialog count after model has loaded

- src/components/modals/EntityExtractor.tsx
Previous check-in used "Feat".  It's case sensitive and didn't push a new package
> feat: force package creation

- cypress/GenerateCypressTestSpecs.js
I was using the back-tick quote on the generated code which omitted the Carriage Return character from the file. Whenever a user hand modified the TestList.js file, but not anything in the masterListOfAllTestCases it would re-generate the file unnecessarily. This creates unnecessary noise in the output and unnecessary need to push in a code change that is not really a change.
> Fix Generate Cypress Test Specs

- cypress/support/Helpers.js
- cypress/support/commands.js
- cypress/support/components/EditDialogModal.js
- cypress/support/components/HomePage.js
- cypress/support/components/ScorerModal.js
Fixes a bug that Matt noticed on CircleCI which is using the Electron browser. The element.innerText property contained New Line characters in them in certain situations.
> fix: inner text function behavior on electron browser

- src/components/modals/ActionCreatorEditor.tsx
Clears the entities when that were added when switching the action type.
I tried the approach to preserve entities as we switch but it ended up being complicated.  It would probably be doable but difficult so we can implement if users get frustrated.  In the worst case the users just re-add the entity which isn't that bad.
If we wanted to preserve it's something like this:
When switching FROM a TEXT type which has entities in the payload thus `requiredEntityTagsFromPayload` greater than 1 we append them to `requiredEntityTags` and reset `requiredEntityTagsFromPayload`
When switching TO to a TEXT type we would have to look at the payload, extract the entities used in it and take them out of `requiredEntityTags` and move them back to `requiredEntityTagsFromPayload`. However, we already …
> fix: clear entity constraints from action when switching type

- src/components/ToolTips/ToolTips.tsx
- src/components/modals/ActionScorer.tsx
- src/react-intl-messages.ts
Removes old code left over from when we had the separate RENDER action's.
See: https://github.com/Microsoft/ConversationLearner-UI/pull/684
Originally we kept the api actions and added render actions but as I was implementing we realialized that we needed to support the passing of information between the two and they would often come in pairs. We since merged them into a single Callback the supports logic and render. 
I didn't remove this at the time.
> chore: remove old/unused Render Action code

- src/routes/App.css
The correct fix is for Slate to update and fix the bug, but in the mean time this appears to work.
See: https://github.com/ianstormtaylor/slate/issues/1436
Action Creator Editor on TEXT:
Before:
After:
on END_SESSION
Before:
After:
> fix: ensure slate placeholder cursor is centered

- src/react-intl-messages.ts
- src/routes/Apps/App/Index.tsx
- src/routes/Apps/App/LogDialogs.tsx
Renames model Tag to model Version to avoid future confusion with Tags on Train Dialogs and to align with LUIS.
**Below model name:**
Before:
After:
**Log dialog column**
Before:
After:
I named the column "Model Version" instead of "Version" to make sure people new it wasn't a version of the log dialog.
> chore: change model tag to model version

- src/components/ExtractorResponseEditor/EntityPicker.tsx
Somehow the entity picker positioning was hard coded to 1em here: https://github.com/Microsoft/ConversationLearner-UI/pull/811/files#diff-47973b78c930c57d97813243b9a3f668R31
I don't know why this was done but it's a bad experience.  The picker is supposed to show up near the selection so it looks like it is related to it and the effect of clicking a entity will do something with the selection.
Before:
After:
> chore: restore ability for entity picker to show above selected text

- src/routes/Apps/App/TrainDialogs.tsx
Originally the icon was on the first column which was first input, then first input was changed to tags, then tags was moved to be second column instead of first and I forgot to move the triangle back.
This moves it back to the first column like below:
Also added a new attribute:
`data-testid="train-dialogs-validity-indicator"` to help make it easier on tests. Previously they were testing for firstInput and having to know if it was valid or not, but the icon isn't actually part of the input so this was misleading.  Even though the first inputs are still in the DOM they don't including the icon so I think there will need to be new way to test this.
Couple questions for further improvement or future PRs:
- **Dates color**
I noticed that we only colorize the scenario, tags, and turns, but …
> fix: move validity indicator icon back to first column

- src/actions/teachActions.ts
When continuing instead of editing the original it would remove the original and add the continued/new dialog which was created as side effect of the new teach session.
This caused the created time to update when it shouldn't have.
The other problem is much more complicated but related:
Due to the way the thunk was written, in combination with other thunks and the asynchronous `await`s inside it, the call to delete the source dialog would finish and remove the dialog from the list before the next call refresh the dialogs which implicitly added it to the list.
Due to created date being changed this caused the dialog to jump/shift in place in the list and depending on server response times could look like the dialog was deleted before it would reappear.
After all is done the dialog properly …
> fix: preserve source dialog instead of new dialog when continuing

- src/actions/teachActions.ts
- src/components/TagsInput.css
- src/components/TagsInput.tsx
- src/components/modals/TeachSessionAdmin.css
- src/react-intl-messages.ts
Fixes the following:
- Prevents creating tags which are whitespace
- Prevents adding duplicate tags to the dialog
- Prevents adding more than 20 tags which was the limit on the server
- Ensures "Tags" label stays at top even though tags list may span multiple rows
- Disable spellcheck since most tags may not be words like "myTag" or "yourTag"
- Fixes incorrectly named error when you create a train dialog from "DELETE" to "CREATE"
In order to show people why the submission doesn't work due to duplicate we had to show an error message so that was added to the right since.
> fix: bugs related to tags

- public/index.css
- src/components/modals/EntityExtractor.tsx
- src/components/modals/ExtractConflictModal.css
- src/components/modals/ExtractConflictModal.tsx
- src/react-intl-messages.ts
Adds additional information to entity label conflict modal.  Aims to improve the following
- Shows the current labels they attempted to submit which were rejected due to conflicts so they can compare it with previously submitted labels and see the problem
- Explains why the bot needs consistent labelling
- Explains what clicking Accept will do.
Future improvements:
Out of scope for PR and I had already talked to Lars about it but I think we eventually should let the user continue even if the labels cause a conflict.  If they had labeled the input incorrectly the first time and now try to label the input correctly this time they can't and are stuck. They won't want to accept changes because they're wrong and closing the dialog does nothing.  They could either stop the dialog or accept the …
> fix: improve entity label conflict modal

- src/routes/Apps/App/Index.tsx
- src/routes/Apps/App/LogDialogs.tsx
On the actual log dialogs page we were excluding dialogs that had been saved as train dialogs.
The meant the count displayed would be incorrect.
There was also bug of the logic to show the empty list placeholder list using a different set of items than the actual list.
Fixes ADO#1943
> fix: show correct number of log dialogs

- src/reducers/logDialogsReducer.ts
Seem to be bug introduced 11 months ago back in this PR: https://github.com/Microsoft/ConversationLearner-UI/pull/500/files#diff-518bcbb8f90efc09b8f2544ec56b56d8R10
Error was only noticed when I moved up the `filter` function which meant it could be called at a time when it's an object instead of an array. We have it typed as an array, so typescript didn't catch it, but after importing a model it would be an object instead of array. I'm still not sure why the reducer allowed you to return values that were not the same type as the expected return value
> fix: ensure logDialogs reducer returns arrays

- src/services/poller.test.ts
- src/services/poller.ts
One of the poller tests was off by 1 millisecond again... relaxing to 590 instead of exactly 600.
I thought if the times were off they could only be later than specified but I guess they can be earlier also.
E.g. if you say `setTimeout` for 50 it can timeout for 50 or more, but apparently it can also timeout for 49...
Also added unique id and random character to visualize logs
> chore: add id to poller for visualizing logs and test output

- public/index.css
- src/components/modals/ActionCreatorEditor.tsx
- src/components/modals/AppCreator.tsx
- src/components/modals/ChatSessionModal.tsx
- src/components/modals/EntityCreatorEditor/EntityCreatorComponent.tsx
- src/components/modals/ExtractConflictModal.tsx
- src/components/modals/PackageCreator.tsx
- src/components/modals/PackageTable.tsx
- src/components/modals/TeachSessionInitState.tsx
- src/components/modals/TeachSessionModal.tsx
- src/components/modals/TutorialImporter.tsx
- src/routes/Apps/App/Actions.tsx
- src/routes/Apps/App/Dashboard.tsx
- src/routes/Apps/App/Entities.tsx
- src/routes/Apps/App/LogDialogs.tsx
- src/routes/Apps/App/Settings.tsx
- src/routes/Apps/App/TrainDialogs.tsx
- src/routes/Apps/AppsListComponent.tsx
- src/routes/Settings.tsx
I noticed some places our buttons have icons and other places they don't so I wanted to see what it looked like it we added them in more places.
Having a visual indicator can be more well-known than language so this might help non-English speakers.
Some of them of simple like, adding + indicator when we create something, but there are many others.
I tried to create image of before / after to see. 
There is still an issue we have to figure out with icon contrast when the button is disabled, so this will have to wait until that is fixed, but wanted to see what people felt about change visually.
There are some other buttons that change the action depending on context such as TeachSessionModal depending if you delete or abandon or continue etc.  I tried to leave those alone for now, but let …
> chore: add icons to buttons

- src/routes/Apps/App/LogDialogs.tsx
- src/routes/Apps/App/TrainDialogs.tsx
Issue with `sort` modifying the array it operates on instead of returning a new array.
In cases where we didn't have any filters applied we were passing the trainDialogs directly to this function.
Fix is to have this function make a copy of array so no matter what it's called with it won't mutate it.
I checked all the other sort cases and they all seem to be using temporary arrays as well and in some cases we were doing this such as `unionMemoryNames.concat([])`.  I think this wasn't exposed as an issue until we switched to `immer` which freezes objects to ensure you aren't mutating stuff in the redux store and this started happening.
I had seen this before and couldn't reproduce reliably.
Fixes ADO#1949
> fix: prevent issue with sort trying modify immutable prop

- public/index.css
- src/components/ExtractorResponseEditor/CustomEntity.css
- src/components/modals/AppCreator.tsx
- src/components/modals/EditDialogModal.tsx
- src/components/modals/EntityExtractor.css
- src/components/modals/EntityExtractor.tsx
- src/components/modals/TeachSessionModal.tsx
- src/components/modals/UserInputModal.tsx
- src/routes/App.tsx
- src/routes/Apps/App/TrainDialogs.tsx
In previous icon change I had skipped the modal buttons since the buttons change behavior based on state of modal / action taken.  The icons should now match that.
There was also a bug due to use of `!important` with the delete icon always being red.
This is fixed.
If this is merged  almost all the buttons should have icons.
It looks like there is a whole bunch of `!important`s to be removed but they are hard to track down since you don't know what it was compensating for so I will have to do those slowly at a later time.
> chore: add icons to modal buttons and fix delete hover

- public/index.css
- src/components/modals/TextboxRestrictable.tsx
- src/routes/Apps/App/Settings.tsx
Minor, just changes the font of the "Deletion is irreversible." to be one of the fonts from Office Fabric.
The old one used different color than the delete button and was custom weight.
Think in future we should stick to these:
https://developer.microsoft.com/en-us/fabric#/styles/typography
It does make the font smaller though so let me know if you want or not.
Before:
After:
> chore: use font matching Office Fabric typography for delete modal

- src/routes/Apps/App/Index.css
- src/routes/Apps/App/Settings.tsx
Combination of error on server not validating and not also checking on client allowed people to put arbitrarily long names for their app in the Settings page after they created it which had really bad efffect on our UI.
UI will now wrap long words, and prevent people from entering long names. There is also associated server PR to fix it there as well.
Before:
After:
Beyond immediate fix, but personally I would like to increase the limit. I think 30 is too short, maybe 50.
Also, our UI could better support long names like LUIS where it is dedicated bar / sub nav, but that's too much work
> fix: enforce app name length on settings page

- src/components/ExtractorResponseEditor/EntityPicker.css
- src/components/ExtractorResponseEditor/EntityPicker.tsx
- src/components/ExtractorResponseEditor/EntityPickerContainer.tsx
- src/components/ExtractorResponseEditor/ExtractorResponseEditor.tsx
The search results prioritize from most relavant at top and least at bottom. As the user searches they would likely be looking at this top to ensure it's the correct element.  When the picker was above without a fixed height it would cause the "top" item to move as the list got smaller making it difficult to read.
Picker and results are now moved below so this item can stay in place as you filter more items out.
Before:
After:
I'm hesitant about this change as I think most selections go on top, but it seems to make more sense when we have this search list changing it's height and things:
Word:
Medium:
> chore: move entity picker below selected text to preserve top search placement

- cypress/support/commands.js
Details on the fix can be found here:
https://github.com/cypress-io/cypress/issues/3730
Chrome v73 broke the code we used to import files. This fixes it.
> Fix Chrome 73 Issue

- package-lock.json
- package.json
- src/components/ActionDetailsList.tsx
- src/components/actionPayloadRenderers/ApiPayloadRenderer.tsx
- src/components/actionPayloadRenderers/ApiPayloadRendererContainer.tsx
- src/components/modals/ActionScorer.tsx
Depends on these PRs:
Only shows functions that were defined/given.  It will help users associate the each action in the list with the callback code for it better. 
Previously it showed both functions always which might confuse a user if they didn't actually define that function.
**Update: had wrong pictures before**
If we go further it could hide functions that don't define any custom arguments.
Issue here is that it violates easy rule to follow that if I wrote a function it will show up in this list.  Now it might be hidden if it didn't use arguments and confuse them thinking it was not defined.
This second view, only hides the logic function if it doesn't define custom arguments. This would make it still usable for the "set entity" case, and less confusing for people who do write …
> feat: only show functions defined in callbacks

- package-lock.json
- src/components/ExtractorResponseEditor/EntityPicker.tsx
- src/components/ExtractorResponseEditor/EntityPickerContainer.tsx
- src/components/ExtractorResponseEditor/ExtractorResponseEditor.tsx
- src/components/actionPayloadRenderers/ApiPayloadRenderer.tsx
- src/components/actionPayloadRenderers/CardPayloadRenderer.tsx
- src/components/actionPayloadRenderers/TextPayloadRenderer.tsx
- src/components/modals/ActionCreatorEditor.tsx
- src/components/modals/ActionPayloadEditor/PayloadEditor.tsx
- src/routes/Apps/App/Dashboard.tsx
- src/routes/Apps/AppsList.tsx
**Shouldn't change any functionality only adding some more protections through Typescript**
In some cases we were assigning the `state` of a component an object of initial values.  
React tried tries to ensure state is `Readonly` here
but when we assign the property directly it seeming overwrote the `Readonly<S>` type inside the component and made it a literal type of the object.
Example of how we would assign state:
This allowed you to assign to the state because it implicitly dropped the `Readonly`. See:
In some cases we explicitly add the `Readonly<ComponentState>` back.
In other cases we have to make sure if any of initialization happens in constructor it all must happen in constructor. Instead of partial initializing and then reassignment properties later which would be violation of …
> chore: ensure component state is readonly

- cypress/integration/CreateModels/WaitVsNoWaitActions.spec.js
- src/components/modals/TeachSessionModal.tsx
Adds `!this.state.hasTerminalAction` check back to `saveDisable` calculation.
Previously it was allowing dialogs be saved without an action.  This caused bugs: 1966, 1964, 1938.
Seems the variable is named `hasTerminalAction` poorly and should be renamed.  I interpreted it to mean the last activity was a bot action, however it only means the dialog contains at least one action not that it ends in an action.
I tested by creating new teach session and noticing it was always true after clicking the first one.
Ironically Brian had made the change to allow this:
https://github.com/Microsoft/ConversationLearner-UI/pull/836/files#diff-1d6c528b0d20670ee41bc043b5358a25L636
Then later opened a bug about it: 
https://dev.azure.com/dialearn/BLIS/_queries/edit/1938/?triage=true
This seems like a …
> fix: ensure dialog has at least one action

- src/components/ToolTips/ToolTipAPI.tsx
Actually uses logicResult in the example that's suppose to demonstrate it.
Fixes the use of the response body to title since the entity was expecting a string.
Also remove types since those are supposed to automatically inferred by typescript and make the example seem more complicated.
Fixes ADO#1871
> chore: correct API callback examples in help panel

- src/components/modals/ActionScorer.tsx
Prevents adding duplicate END_SESSION actions.
Also prevents adding END_SESSION when it's not the last action.
Seems like this was used in some places like `isUnscoredActionAvailable` but this relies on an `UnscoredAction` instead of regular `Action` which doesn't have the `reason` attribute.  Could have cased the action and reworked this method but I thought it was more confusing.
> fix: prevent auto adding new end session action if not available

- src/components/ToolTips/ToolTips.tsx
Seems alternative was spelled wrong and somehow the text was duplicated, maybe during a merge it accepted both changes instead of keeping one.
Fixes ADO#1995
> chore: remove duplicate help panel text

- src/components/ActionDetailsList.tsx
Was missing an implementation for `END_SESSION` actions.  It should be similar to the `TextAction` since they both use a single payload. Glad we put these warnings in.
Fixes ADO#1999
> chore: add end session sort value

- src/components/ToolTips/ToolTips.tsx
- src/components/modals/PackageTable.tsx
- src/react-intl-messages.ts
- src/routes/Apps/App/Settings.tsx
We introduced tags on dialogs which caused rename of model tags to model versions, but didn't rename everything related.
Here is new picture:
Think it needed a description to show people use cases and why they might want to use versioning.  Looking for feedback.
Does creating a snapshot always use the live version?
Also, should we change the words "Editing Version" since you can't edit version?
> docs: use consistent language around model versions

- src/components/ExtractorResponseEditor/EntityPickerContainer.tsx
Removes the `matchedOptions` from the initial state so it doesn't get reset.
Will probably refactor this mess after release, but this should be temporary fix.
Alternate is to revert both the previous commits and put it back to original. Basically had a bug in the component since the beginning where it kept mutating `initialState` which is supposed to be static as the initial state for the component so even though we were resetting it by setting `initialState` it wasn't resetting `matchedOptions` and when you could look at the definition of `initialState` and see it's an empty array but it's actually not at runtime. Very confusing.
> fix: entity picker reset bug

- src/components/ExtractorResponseEditor/EntityPickerContainer.tsx
Previously did work not to reset the options so they don't get set back to an initial empty array and but forgot about the case where we do need to reset them back to default options list when it's opened.
> fix: reset matched options to default when opened

- .circleci/config.yml
In order to enable the ability to cancel the redundant builds we needed to be on 2.1
> build: enable 2.1 and pipelines to reduce redundant

- src/routes/Apps/App/LogDialogs.tsx
- src/routes/Apps/App/TrainDialogs.tsx
sourceTrainDialogId shouldn't be set when dialog is new
> fix: bug 2058 bad replacement call when not needed

- src/routes/Apps/App/TrainDialogs.tsx
But search filter is still active
> fix: bug 2082 search field erased when return from tree view

- src/components/Webchat.tsx
- src/reducers/settingsReducer.ts
- src/reduxStore.ts
- src/types/const.ts
There were many different fixes here.  Some blatant typo errors and others initialization and store / storage errors.
In summary, previous changes stopped storing the `botPort` but left the initialization of the `reduxStore` to use this object which no longer had `botPort`.  This meant `botPort` was undefined when being used by `Webcat` which explains why it never set the conversation reference because it never connected to the SDK and failed silently.
This now adds protection in Webchat so it throws an error if `botPort` is not set instead of failing silently.
Originally we were storing the `botPort` in localStorage and always sending requests to that port.  When we changed the UI to run on the bot and wanted it to communicate with this port from the URL we introduced some complexity as …
> fix: settings.botPort was undefined

- src/components/ExtractorResponseEditor/ExtractorResponseEditor.tsx
- src/components/modals/EntityExtractor.tsx
Adds "Create Entity" button to Extractor to allow creating ENUM entities during creation of dialog.
Also adds comment clarifying used of `entityTypeFilter` and `builtInTypeFilter`
> feat: allow creating any entities during extraction

- src/components/modals/ActionScorer.tsx
Turns out we could pass `ScoredBase` in all cases since it was forcing the score to be `undefined` when generated the `ScoredAction` in the function.
Major change is removal of lookup of action from scoreResponse again since it was already passed to the funtion.  I think in previous implementation the server was not returning a complete set of `unscoredActions` using the latest source but now it does so it should be safe to remove the search.
The other case where you create the action inline during dialog creation is handled inside the `ActionScorer` and waits until the action exists before calling `handleActionSelection` so I think that should be ok also.
>  fix: handleActionSelection takes scoredBase instead of actionId

- public/index.css
- src/components/modals/PackageTable.tsx
- src/components/modals/index.ts
- src/react-intl-messages.ts
- src/routes/Apps/App/Settings.css
- src/routes/Apps/App/Settings.tsx
Given the importance of versioning I wanted to see how it would look with different design that increases information and discovery. The current design has creation button and version description hidden which could lead users to avoid using it or knowing how to create one.
Making version creation button visible by default is probably the most important change.
Adds new header for "versions" section.
Removes the border from bottom header since that wasn't the "start" of the section but I could add it back.
> chore: restructure app versions on settings

- src/reducers/settingsReducer.ts
- src/reduxStore.ts
Make the bot port settings more robust to corrupt objects. Still not quite sure how it was getting set incorrect after a browser refresh or open/close, but this hopefully ensures it's always correct by setting it to something acceptable if it's not.
> fix: bot port undefined

- src/components/modals/ActionCreatorEditor.tsx
Previously the enum entities were always expanded into their conditions.
This meant when you opened an item that used the enum entity in the payload to display it's value it would still expand set these as the initial state of the picker.
This was further complicated because if you edited and resaved the action it would then persist these conditions to the server which are duplicated and mutually exclusive.
This now prevents expansion but there are still other issues with showing mutually exclusive or showing options that should have no effect.
>  fix: prevent expansion of enum entities when opening

- package-lock.json
- package.json
Been watching this one for a while, they finally merged a fix! 
https://nvd.nist.gov/vuln/detail/CVE-2019-10742
https://github.com/axios/axios/pull/1485
We use another package in the SDK which depends on axios so will likely have to update that one when a fix is published.
This one wasn't caught by `npm audit` but there are other similar suggested changes. Will have to understand more about the `npm audit` suggested fixes and maybe submit those in different PR.
> fix: upgrade axios to 0.19.0

- cypress.json
- cypress/integration/actionDeletion.spec.ts
- cypress/integration/actionModal.spec.ts
- cypress/integration/descriptionAndTags.spec.ts
- cypress/integration/entityConflicts.spec.ts
- cypress/integration/entityPicker.spec.ts
- cypress/integration/setEntityActions.spec.ts
- cypress/support/constants.ts
- cypress/support/selectors.ts
- cypress/support/utilities.ts
I had noticed and fix various things as I was going through smoke test development, wanted to separate some of the UI changes from the larger test PR.
There were various mis-used CSS selectors for example using `.cl-action-creator-fieldset` on things other than the `ActionCreator`.
Also change to properly use cypress baseUrl, log dialog description testid, and package creactor modal to use consistent modal styles
Updates: Something was going on with interpreation of the `support/index.js` file which I didn't change and now appears to be working correctly. I had split out the UI changes thinking they shouldn't affect tests, already merged that and now doing the test stuff.
It primarily is using the `baseUrl` and updating utilities
> test: prep for smoke tests, separate UI changes

- .circleci/config.yml
- package-lock.json
- package.json
Adds 'wait-on' to CI builds to be more proper.
Current CI builds rely on cypress waits in the cy.visit() command. It should rely not start tests unless the bot and ui are started successfully.
>  test: use wait-on for CI runs

- src/react-intl-messages.ts
- src/routes/Apps/App/TrainDialogs.css
- src/routes/Apps/App/TrainDialogs.tsx
Adds button to clear filters.
If you manually added a filter or implicitly added by coming from an action this helps to clera the filters.
Before you would have to manually select the dropdown and scroll to select the "All *" option. This does it one click and is also a visual indicator if the filter is set.  For examplle if you enter a search term it might be only showing 9 of the total 10 dialogs and you could think you're looking at the complete set but you are not. 
Update: Temporarily disregard the amount of files and changes in the PR. I had to rebase on another PR to get the models change and that PR is stuck.  Will fix this when that PR is fixed.
> feat: add button to clear/reset dialog filters

- package-lock.json
- package.json
Similar to models PR, there was task to update handlebars but there are many other things to also fix.
The command also updates `react-scripts-ts` which was worriesome and didn't built propertly so I reverted that package change but kept the others.
Also `react-scripts-ts` is deprecated. I had tried to upgrade and our app does work fine on the official version. The only downside I saw was different in setting breakpoints due to change in sourcemaps.  I'm not sure much how to fix that and I think it's important to preserve so I didn't do the full change yet.
>  chore: audit fix force (without breaking change to react-scripts-ts)

- src/components/CLTagPicker.css
- src/components/CLTagPicker.tsx
- src/components/modals/MergeModal.tsx
The rendering and classes of the TagPicker changed and this updates the classes.
Before:
After:
There was also use of `DialogFooter` component outside of a `Dialog` which caused horizontal scrolling on the MergeModal. This now uses the `cl-modal-footer` with button s
It seems we would have to refactor a lot modal in future, but should fix the bug for now.
> fix: visual defects due to office 6.x 

- src/services/poller.ts
There was ADO bug 2135 which has since been closed and not reproducable but these changes might mitigate if it happens again.
As comment says, I believe there is weird condtion where the array has an `undefined` injected into it which is then processed later. This shouldn't be possible based on single threaded code and executing till completion which ensure the `undefined`s are filtered out before processed however it's the only way I think this bug can occur.
>  fix: prevent poller undefined issue

- src/components/modals/ActionPayloadEditor/PayloadEditor.tsx
- src/components/modals/ActionPayloadEditor/Picker.tsx
- src/components/modals/ActionScorer.tsx
- src/components/modals/EntityCreatorEditor/EntityCreatorComponent.tsx
- src/components/modals/EntityExtractor.tsx
- src/components/modals/TreeView/TreeView.tsx
- src/routes/Apps/App/Actions.tsx
With the upgrade to 6.x we can use proper react refs now:
https://reactjs.org/docs/refs-and-the-dom.html#creating-refs
Also learned a bit about the `forwardRef` component that allows getting refs of internal DOM elements which is nice as it exposes standard `ref` prop instead of needing a custom prop
> fix: use react ref objects instead of callback refs

- src/routes/Apps/App/Entities.tsx
- src/routes/Apps/App/LogDialogs.tsx
- src/routes/Apps/App/TrainDialogs.tsx
I'm seeing these errors in some of the tests. 
```
Uncaught TypeError: Cannot read property 'focus' of null
This error originated from your application code, not from Cypress.
When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.
https://on.cypress.io/uncaught-exception-from-application
```
I'm guessing it is another race condition where most of the time the button is assigned before we call `focus()` but in some cases it isn't assigned yet.
I need to find a way to reproduce this and debug, but my guess is there is problem with this pattern:
```
// Wrong type - should be OF.IButton | undefined since it's …
```
> fix: prevent Cannot read property 'focus' of null

- cypress/support/components/HomePage.js
I'm not quite sure what happened here.  I assume this broke because of change to 6.x office fabric where they removed a `div` yet it was said tests had been passing. You can see DOM doesn't have the div.  This selector was overly specific anyways.
`CypressError: Timed out retrying: Expected to find element: '[data-testid="model-creator-import-file-picker"] > div > input[type="file"]', but never found it.`
> fix: file import selector

- src/routes/Apps/App/LogDialogs.tsx
I assume you wanted the modal to use confirmation button instead of ok:
Fixes ADO#2189
> fix: log dialog delete confirmation

- src/components/ExtractorResponseEditor/utilities.ts
Apparently there was possibility of text being labeled incorrectly (had proper indicies but incorrect text) and this was bad data in the train dialogs.
This adds check to ensure that doesn't happen.  It's an older bug though so perhaps it was fixed.
Fixes ADO#1475
> fix: add check for mismatch between label indicies and text

- src/components/actionPayloadRenderers/ApiPayloadRenderer.tsx
- src/components/actionPayloadRenderers/CardPayloadRenderer.tsx
- src/components/actionPayloadRenderers/TextPayloadRenderer.tsx
- src/components/modals/ActionCreatorEditor.tsx
- src/components/modals/AppCreator.tsx
- src/components/modals/EditApiStub.tsx
- src/components/modals/EntityCreatorEditor/EntityCreatorComponent.tsx
- src/components/modals/EntityCreatorEditor/EntityCreatorContainer.tsx
- src/components/modals/EntityExtractor.tsx
- src/components/modals/MemorySetter.tsx
- src/components/modals/PackageCreator.tsx
- src/components/modals/TextboxRestrictable.tsx
- src/components/modals/UserInputModal.tsx
- src/routes/Apps/App/Settings.tsx
- src/routes/Apps/App/TrainDialogs.tsx
were getting a bunch of decprecation warnings after the upgrade to 6.x
mainly using standard `onChange` and `placeholder` properties where possible. There were a few such as `onChangeCardOption` or `onChangeActionType` that couldn't be changed because they were called programmatically outside of user events.
Should clean them up. The diff for `MemorySettings` looks larger then it should be because it wasn't formatted earlier.
> fix: office fabric warnings

- src/components/ActionDetailsList.tsx
- src/routes/Apps/App/Entities.tsx
- src/routes/Apps/App/LogDialogs.tsx
- src/routes/Apps/App/TrainDialogs.tsx
- src/routes/Apps/AppsListComponent.tsx
Previously we didn't show an arrow indicating the sorted column. This could mislead users into thinking the list is not sortable.  Also if you clicked the column it would be not sort the first time.
This fixes both of those issues.  I need to create a code pen for Office fabric as this seems like a bug, but basically the `column` object received in the `onClickColumnHeader` function is not the same as one of the columns even though it has the same shape.
We have to manually find the matching column by `key` and I'm not sure why that matters.
>  fix: show sort arrow by default and sort on first click

- src/routes/Apps/App/LogDialogs.tsx
Had accidentally set the filter function to use the logs from state, this meant the filter could only ever become more constrained because it could only filter from previously filtered results instead of the entire set.
Fixes ADO#2195
> fix: log searching through props instead of state

- .circleci/config.yml
This should fix a recent change that caused regression (.js) test results to be lost.
Once I verify this is working I will be checking it in.
> fix: test results that were being discarded

- src/components/ActionDetailsList.tsx
- src/routes/Apps/App/Entities.tsx
- src/routes/Apps/App/TrainDialogs.tsx
- src/routes/Apps/AppsListComponent.tsx
Since I did the work for selection on LogDialogs list we learned the trick to enable single click invocation on items.
We can now use the proper `onItemInvoked` instead of `onActiveItemChanged`. The allows right click and many accessibility improvements such as keyboard navigation and 'Enter' for selection.
Fixes: ADO#1519
> fix: use onItemInvoked instead of onActiveItemChanged

- src/components/ExtractorResponseEditor/PreBuiltEntity.tsx
- src/components/ExtractorResponseEditor/PreBuiltEntityNode.tsx
- src/components/ExtractorResponseEditor/models.ts
- src/components/ExtractorResponseEditor/utilities.ts
Remove old code when resolvers were added
Related PRs for tracking:
https://github.com/microsoft/ConversationLearner-UI/pull/792/files#diff-0516be742b5d150780ab0a12838b8d1dR599
https://github.com/microsoft/ConversationLearner-UI/pull/791/files#diff-ecfa596a555464dcfc9af80d0fc3be98R268
Fixes ADO#2200
> fix: restore blue coloring or noneditable entities

- src/components/ActionDetailsList.tsx
- src/routes/App.tsx
- src/routes/Apps/App/Entities.tsx
- src/routes/Apps/App/LogDialogs.tsx
- src/routes/Apps/App/TrainDialogs.tsx
- src/routes/Apps/AppsListComponent.tsx
After enough experimenting/process of elimination with my own recreation and their demo it seems the `getKey` and `setKey` were needed instead of only the `getKey` on the selection.  Still am not sure why the selection is preserved on train dialogs bug seemingly reset on log dialogs when the filter exludes the selected items. Also noticed they released office 7.x so will be looking into that.
Also, try to normalize sorting pattern on various lists, and fix the spacing of loading indicators for the app
>  fix: use DetailsList getKey and setKey to use render computed dialogs

- src/components/modals/ActionCreatorEditor.tsx
Help tooltips for the AdaptiveCard parameters were incorrectly referencing API terminology; fixed enum to pull the Card help tooltips.
> fix: update TipType for CARD actions to ACTION_CARD

- src/Utils/dispatchUtils.ts
- src/actions/trainActions.ts
- src/components/ToolTips/ToolTips.tsx
- src/components/modals/AppCreator.tsx
- src/components/modals/DispatcherCreator.tsx
- src/react-intl-messages.ts
- src/routes/Apps/App/TrainDialogs.tsx
- src/routes/Apps/AppsIndex.tsx
- src/routes/Apps/AppsList.tsx
- src/routes/Apps/AppsListComponent.tsx
- src/types/const.ts
- Move to dedicated modal since the other is very overloaded with unrelated concerns.
- Re-organized / re factored algorithm code (`dispatchUtil`) to be more readable and have better facades points.
- Renamed existing to DeterministicSingleTransfer
- Added RandomSingleTransfer
- Note: RandomMultiTransfer is not implemented. Need to go over it with Lars as it's very different from the first two. (Think it was select N rounds subset from random dialogs and concat to larger dialog. Will likely be hard to tell if it's written correctly)
Interesting idea during algo design that I realized the number of transition points within a dialog could be dependent on the dialog and instead of be fixed value like (Attempt up to 5 transition points).
E.g. A small dialog of 7 might try to transition in 4 …
>  feat: enable dispatch algorithm selection

- src/components/modals/EditDialogModal.tsx
- src/routes/Apps/App/TrainDialogs.tsx
Fixes ADO#2054
Latest updates to tags and description were getting lost because it was using them from the state of traindialog instead of updated state which may have edits.
> fix: save tags and description on replayed dialog

- src/components/modals/ActionCreatorEditor.tsx
Fixes ADO#2228
In default OF behavior there are no tags shown when you click into the picker. The user has to enter characters to narrow serach and once tag is shown it defaults to selecting on dismis to preserver their effort.
In our case we changed the default to show all tags, so when the user clicks away they likely didn't want the top tag.
Changes to not select it anymore.
> fix: prevent picker from auto selecting top tag on dismiss

- src/routes/Apps/App/TrainDialogs.tsx
Fixes ADO#2255
There was code to remove the param when closing the EditDialogModal `onCloseEditDialogModal` but there was not when closing the Teach Session `onCloseTeachSession`
When you continued a dialog and abandoned the edits you could not open that dialog anymore because the ID was still present and when clicking to push id on the history it looked the same as previous history and was skipped. Probably a few more cases where this might occur and don't like the feeling of adding removal code on all the potential close paths.
Seems like the query param should synced with the state so it can't be wrong. E.g. when dialog is active, query param is added, when dialog is not active param is removed. However this already goes against our working code because we activate a dialog by manually …
> fix: remove query param on teach abandon

- src/components/actionPayloadRenderers/SessionPayloadRenderer.tsx
- src/components/actionPayloadRenderers/SessionPayloadRendererContainer.tsx
Can't remember exactly, but think in process of trying to make EndSession actions more easitly distinguished from Text actions we created it's own renderer with the italic prefix, but forgot to include the toggle switch.  Adds the toggle switch
> fix: add toggle to Session renderer

- src/components/modals/ActionCreatorEditor.tsx
Seems there was regression when `clientData` was added to actions to allow duplicate actions.
This object needs to match was the server returns.
> fix: prevent creating duplicate actions

- src/Utils/util.ts
There was utility added that used `toUpperCase()` on one side but not the other.
Purpose is to eliminate casing from matching for both the features and feature string. User shouldn't have to remember if it's "cci" "Cci", or "CCI", they all should work and easier to explain to people.
> fix: use same case on feature string matching

- src/components/modals/EntityCreatorEditor/EntityCreatorContainer.tsx
Noticed this while working on other bug. This error check wasn't run when editing, I assume because we didn't allow entity rename before. Now that we do it should be run in both cases.
> fix: check name in use when editing

- cypress/fixtures/isResolutionRequired.cl
- cypress/integration/regressionTs/isResolutionRequired.spec.ts
- cypress/support/selectors.ts
- src/components/modals/EntityCreatorEditor/EntityCreatorComponent.tsx
- src/components/modals/EntityCreatorEditor/EntityCreatorContainer.tsx
There was bug where option should show true regardless of actual entity value due to the force check / uncheck logic. Since the property is non-editable, it is now disabled when editing.
- Also adds e2e tests for checkbox behavior and actual extraction logic.
- Removed extra `isEditing` boolean
```
Resolution Required
Entity Option Behavior
New Entity
√ given NONE resolver type should be disabled and unchecked (54033ms)
√ when resolver type change from NONE to other, checkbox should be enabled and checked (286ms)
√ when resolver type changes from other to NONE, checkbox should be disabled and unchecked (272ms)
Editing
√ should be disabled when editing (3615ms)
Entity Label Behavior
√ given no resolution, entity label with option False should be allowed and label with option True should be …
```
> fix: preserve isResolutionRequired when editing and add tests

- src/routes/Apps/App/Index.css
- src/routes/Apps/App/LogDialogs.tsx
I'm not sure why the selection object isn't reset when it's source doesn't exist anymore (list is removed from DOM).  I asked on the OF teams channel so we'll see if they have better solution.
This works for now.
Fixes ADO#2307
> fix: keep DetailsList in DOM to correct log selection when deleting

- src/components/ExtractorResponseEditor/ExtractorResponseEditor.tsx
Fixes: ADO#2264
**Why was the entity overlay added?**
We used to allow users to freely select text. This was a established behavior they would expect from other program like notepad or Word and some time ago this overlay was put in and diverged from that behavior. Likely to protect against some error but what was it? In other words, previously there was no concept or requirement to UNselect something, the new selection would over write the old one. Now the users have to click again.
There is also duplicated state in the extractor editor and the custom entity node. From my testing it was because the node is not re-rendered and needs this, but it's going against standard react patterns of lifting state to parents, This is example of thing that would be better to capture comments.
> fix: remove entity overlay when switching extraction

- src/components/actionPayloadRenderers/CardPayloadRendererWithHighlights.tsx
Fixes ADO#2220
Click event to view card was going through to list.
> fix: prevent list row invocation when viewing card

- .circleci/config.yml
- cypress/integration/smoke/required/placeholder.spec.ts
Adds separate smoke job in order to have separate github check which can pass or fail independently of the others.
We had a smoke folder but it was only used by the sample repo. Eventually you should be able to put which ever tests you want in this folder and to have them run.
Would need to preserve the existing smoke test for samples. ~If there needs to be change to avoid executing `apiCoverage` test then you would need to add more folders and change paths in cypress commands and update samples to refer to this new path.~ Created a new "required" folder for tests you would like to run.
~Likely won't pass in first couple of runs as trying to see if we can re-use sections of the YAML instead of duplicating job definition.~
Added `commands` …
> test: add smoke test job

- src/Utils/dialogEditing.ts
- src/Utils/obiDialogParser.ts
- src/Utils/obiUtils.tsx
During .dialog import, we check to see if a given action or entity has already been created by looking them up in app memory (TrainDialog's `actions` or `entities` props).  Invoking the `create...ThunkAsync` does not update props while importing a set of dialogs; accordingly, without this change, the import will try to create the same action/entity multiple times, if the same action/entity is referenced in multiple dialog steps.
Tested via import of the product key intent v4 files.
> fix: store newly-created entities and actions in app memory

- package-lock.json
- src/Utils/obiDialogParser.ts
This PR breaks apart OBI .dialog file into discrete steps : 
1. Generation of the dialog tree structure
2. Building TrainDialogs from each walk of the dialog tree
This is a precursor to adding support for SwitchCondition statements, which are complicated in that they generate dialog branches (similar to `rule` elements) but also can contain content (similar to `step` elements).
> feat: OBI dialog import as a tree walk

- package-lock.json
- src/Utils/obiDialogParser.ts
In OBI .dialog files, some steps in the tree can carry an "intent", which is a dialog sub-tree classification such as `Product_Key_Service_Integration_main` or `End_of_Conversation_main`.  We use this "intent" as a proxy for user utterances in the generated train dialogs :
This PR fixes 2 edge cases during .dialog import.
1. Nodes that have an incoming intent but no actions other than redirection to other dialog nodes
2. Nodes that have actions but no incoming intents
**For (1)**, the current node's intent was only used if the node also generated actions; this would cause the intent to be dropped if the only action was to redirect to another dialog node.
To fix this, the intent is carried forward through the recursive handling of the dialog tree if it's not used in the generation of a …
> fix: handle edge cases for OBI .dialog import

- package-lock.json
- src/Utils/obiDialogParser.ts
- src/Utils/obiUtils.test.ts
- src/Utils/obiUtils.tsx
- src/routes/Apps/App/TrainDialogs.tsx
- src/types/obiTypes.ts
This PR adds initial support for `SwitchCondition` .dialog nodes.
* Branches from the `SwitchCondition` are traversed and included in construction of the dialog tree
* Conditions from each `SwitchCondition` case are used to generate enum entity values
* Eg, if a switch has cases for `isProductKey == Windows` and `isProductKey == Office`, we will generate an enum entity `isProductKey`  with values `Windows` and `Office`:
Not implemented in this PR (coming later):
* Setting bot memory following the API call
* Adding "condition" restrictions to the actions generated from switch statements
* Generating turns for the input and output values of the API call
* Unit testing against interesting .dialog structures
Notes:
* Condition values are truncated to 10 characters during enum creation.  If …
> feat: Handle SwitchCondition nodes in .dialog import

- src/components/modals/ActionCreatorEditor.tsx
Split out the Fabric update PR https://github.com/microsoft/ConversationLearner-UI/pull/1343 as I want to reduce variables. The should prevent the modal from opening which was known bug breaking the tests. Hopefully we can get smoke tests passing before upgrading Office Fabric
> fix: remove getTextFromItem

- package-lock.json
- src/components/ExtractorResponseEditor/ExtractorResponseEditor.tsx
Cypress event tool can optionally choose row to select from.  Is backwards compatible:
Select "hello" in the 2nd row
```
var event = new CustomEvent("Test_SelectWord", { detail: { phrase: "hello", index: 1 })
event.initEvent("Test_SelectWord", true, true)}
element.dispatchEvent(event)
```
or default to the first row
```
var event = new CustomEvent("Test_SelectWord", { detail: "hello")
event.initEvent("Test_SelectWord", true, true)}
element.dispatchEvent(event)
```
> feat: add row selection to cypress label event

- src/components/actionPayloadRenderers/PayloadRendererWithHighlights.tsx
- src/components/modals/ActionPayloadEditor/MentionNode.tsx
- src/components/modals/ActionPayloadEditor/slateSerializer.ts
- src/components/modals/ActionPayloadEditor/slateTransformer.ts
A while back I added highlighting to entities. At that time we only dealt with incomplete nodes inside the action creator editor but now we also have to deal with them inside this payload renderer.
- Adds check for `complete` property
- Changes from `throw` ing errors to logging `warnings`
> fix: don't highlight incomplete nodes

- cypress/support/selectors.ts
- src/routes/App.css
When we changed the UI to have the grey banner / sub navigation per model I changed the selectors available and forgot to update the test.  As I was going through tests on new build/repo I discovered this.  Porting back to this repo.
> fix: release test - app selector

- cypress/support/Helpers.js
- cypress/support/components/ActionModal.js
I had changed the cy.ExactMatch command to behave more like the cy.contains command in terms of the number of elements it returns, however this caused too many tests to fail and the fix was necessary for only one function. So I worked out how to fix the issue for that one function without affecting all of the other tests.
> Fix Bug in cy.ExactMatch Command

- src/components/modals/ConditionModal.tsx
There was assumption that the filter function wasn't executed since if having a condition, would imply there must be entities/options available for the condition. However, we can have stale conditions exist even when no suitable entities exist due to edits.
> fix: prevent crash when accessing undefined selected option

- src/components/modals/AppCreator.tsx
As code comment says "Component might update before `localeOptions` have been loaded" meaning their might not be first value and should default to empty string again
> fix: empty string fallback for undefined locale

- src/components/ExtractorResponseEditor/ExtractorResponseEditor.tsx
Defaults `tokens` to empty array when there is no element to use query selector on.
Unsure how this is possible given the `index` check just above it.  Suppose one of the `rows` is undefined.
> fix: prevent queryselector of undefined

- src/routes/Apps/App/TrainDialogs.tsx
update train dialog validity flags on replay from train dialog list view
> fix: bug 2356

- src/components/ExtractorResponseEditor/utilities.test.ts
- src/components/ExtractorResponseEditor/utilities.ts
Adds two functions
`warnAboutOverlappingEntities` which detects overlapping entities and logs warning to the console so we can look out for this in future. In most case we should never see these warnings, but if we do we know somethings wrong.
Note the output shows in test logs, but is intentional to send warning for browsers.
`discardOverlappingEntities` which removed the overlapping entities from rendering in the extractor editor. Alternative seems like throwing an error since we can't render them properly.
In long term we should probably support overlapping labels but there was talk of using LUIS extraction editor in future so likely bad investment.
Picture of warning.
> fix: discard overlapping entities for proper render

- cypress/support/PersistentLogs.js
Changed the naming convention for log files so that it helps evaluate test failures. Applying this change first and quickly so once I introduce the web page app it will work with the most recent builds.
> Persistent Logs

- cypress/support/MonitorDocumentChanges.js
Captures the UI Error Panel in the tests log. This gives us the chance to use our automated test result analysis tool to see when the error panel is present in a test run that failed so as to identify it as a known bug.
> Capture Error Panel in Test Log
